/**
 * Font assets for the Typst preview compiler.
 *
 * The preview compiles in the browser through `@myriaddreamin/typst.ts` (a WASM
 * build of Typst), so it reads no system fonts — only the ones registered with
 * its font loader. Without them, a document that names a font the compiler does
 * not ship renders a fallback and reports `unknown font family: <name>`, which
 * is what the proposal templates trigger.
 *
 * `typst.ts` ships a small default set and `preloadFontAssets` can add two
 * groups from a CDN. Those groups leave real gaps for these templates: the CJK
 * group carries only regular-weight serif faces, so bold Chinese text — which
 * every section heading uses — has nothing to resolve to.
 *
 * These are registered as plain URLs, which the font loader fetches eagerly on
 * the first compilation — roughly 7 MB once per browser, all of it before the
 * first PDF appears. That cost is accepted deliberately: the alternative is
 * per-face lazy loading through `add_lazy_font`, which needs each font's family
 * and weight metadata up front (only obtainable by downloading the file and
 * parsing it with `getFontInfo`), and that metadata file would have to be
 * regenerated by hand whenever this list changes.
 *
 * The CJK faces are ~1.3 MB each and account for most of the weight. They are
 * not bundled as build assets instead, because that would put the same bytes in
 * the frontend image for every user, including those who never open a preview.
 *
 * Every entry below is verified to exist at the pinned tag. The two repositories
 * do not hold the same files, and their `main` branch holds more than the tag
 * does — listing a face that the tag lacks yields a 404 at compile time and the
 * font silently never loads, so the source of each entry matters.
 *
 * Fonts that are deliberately absent because they cannot be shipped:
 * - SimSun / Times New Roman — proprietary, not redistributable.
 * - Source Han Serif SC / FandolSong / FandolHei — not published in either
 *   asset set. The templates keep them as later fallbacks, which is harmless:
 *   an unresolved entry in a fallback chain only costs a warning, and the
 *   earlier entries cover the same glyphs.
 */

/** Upstream Typst asset repositories, pinned to the version `typst.ts` defaults to. */
const TYPST_ASSETS =
  "https://cdn.jsdelivr.net/gh/typst/typst-assets@v0.13.1/files/fonts/"
const TYPST_DEV_ASSETS =
  "https://cdn.jsdelivr.net/gh/typst/typst-dev-assets@v0.13.1/files/fonts/"

/**
 * Faces added on top of the `typst.ts` defaults.
 *
 * Chosen to cover what an academic proposal mixes: CJK serif body text with a
 * bold weight, Latin serif that pairs with it, a sans for headings, and math
 * for the equation-heavy method sections. One file per weight — with eager
 * fetching, every entry is bytes the user waits for, so the list stays the
 * smallest set that covers the templates' declared fallback chains.
 */
export const TYPST_EXTRA_FONTS: string[] = [
  // CJK serif, simplified and traditional, regular and bold. Bold is the gap
  // in the default set, and the reason Chinese headings cannot render.
  `${TYPST_DEV_ASSETS}NotoSerifCJKsc-Regular.otf`,
  `${TYPST_DEV_ASSETS}NotoSerifCJKsc-Bold.otf`,
  `${TYPST_DEV_ASSETS}NotoSerifCJKtc-Regular.otf`,
  `${TYPST_DEV_ASSETS}NotoSerifCJKtc-Bold.otf`,
  // Latin serif + math, from the group `typst.ts` already preloads for text.
  `${TYPST_ASSETS}LibertinusSerif-Regular.otf`,
  `${TYPST_ASSETS}LibertinusSerif-Bold.otf`,
  `${TYPST_ASSETS}NewCM10-Regular.otf`,
  `${TYPST_ASSETS}NewCM10-Bold.otf`,
  `${TYPST_ASSETS}NewCMMath-Regular.otf`,
  // Sans for headings, and a Latin face for language coverage.
  `${TYPST_DEV_ASSETS}Roboto-Regular.ttf`,
  `${TYPST_DEV_ASSETS}Ubuntu-Regular.ttf`,
  `${TYPST_DEV_ASSETS}IBMPlexSans-Regular.ttf`,
  `${TYPST_DEV_ASSETS}IBMPlexSerif-Regular.ttf`,
]
