// This file is auto-generated by @hey-api/openapi-ts

/**
 * 登录前同意隐私协议请求（需要邮箱密码验证）。
 */
export type AcceptPrivacyPolicyRequest = {
    email: string;
    password: string;
};

/**
 * 获取进化块分析建议结果的响应体。
 */
export type AdvisorDetailResponse = {
    task_id: string;
    advisor_type: string;
    status?: (ReportStatus | null);
    /**
     * 分析结果数据
     */
    data?: unknown;
    error?: (string | null);
    updated_at?: (string | null);
};

/**
 * 进化块分析建议生成请求体。
 *
 * Attributes:
 * goal: 算法演化目标描述。
 * language: 输出语言。
 * provider_id: LLM Provider ID，格式同 ReportGenerateRequest。
 * model_name: 指定模型名称，覆盖 Provider 默认模型。
 */
export type AdvisorGenerateRequest = {
    /**
     * 算法演化目标描述
     */
    goal: string;
    /**
     * 输出语言：'zh' 表示中文，'en' 表示英文
     */
    language?: 'zh' | 'en';
    /**
     * LLM Provider ID；支持 null/'default'/'mock'/真实UUID
     */
    provider_id?: (string | null);
    /**
     * 指定使用的模型名称；未提供时使用 Provider 默认模型
     */
    model_name?: (string | null);
};

/**
 * 输出语言：'zh' 表示中文，'en' 表示英文
 */
export type language = 'zh' | 'en';

/**
 * 触发进化块分析建议生成后的响应体。
 */
export type AdvisorGenerateResponse = {
    task_id: string;
    /**
     * 'block_advise' 或 'block_recommend'
     */
    advisor_type: string;
    status: ReportStatus;
    message: string;
};

/**
 * 参数配置 JSON Schema 响应。
 */
export type AppConfigSchemaResponse = {
    /**
     * AppConfig 的 JSON Schema
     */
    config_schema?: {
        [key: string]: unknown;
    };
};

export type Body_live_codes_add_targets = {
    /**
     * 真实群码图片，可多张
     */
    files: Array<((Blob | File))>;
    /**
     * 有效天数，<=0 表示永不过期，默认 7
     */
    valid_days?: number;
    /**
     * 扫码次数上限（近似人数），留空表示不限
     */
    scan_limit?: (number | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * 内置供应商额度信息响应。
 */
export type BuiltinProviderQuotaResponse = {
    available?: boolean;
    provider_id?: (string | null);
    provider_name?: (string | null);
    spend?: (number | null);
    budget?: (number | null);
    remaining?: (number | null);
    currency?: string;
    message?: string;
};

export type chat_tune_chat_tune_upload_data = {
    /**
     * 上传的文件列表（filename 可含 / 以表达子目录结构）
     */
    files: Array<((Blob | File))>;
};

export type chat_tune_chat_tune_upload_file = {
    /**
     * 上传的文件列表
     */
    files: Array<((Blob | File))>;
};

/**
 * 调参会话当前激活的阶段。
 *
 * 默认激活需求收集阶段；任意一个后台协程开始执行都会把激活阶段
 * 更新为对应值（无回退语义，只反映"最近一次启动了哪个阶段"）。
 */
export type ChatTuneActiveStage = 'gathering' | 'build' | 'review';

/**
 * 单条调参消息的响应模型。
 */
export type ChatTuneMessageItem = {
    id: string;
    session_id: string;
    turn_id: string;
    role: ChatTuneMessageRole;
    content: string;
    turn_status: ChatTuneTurnStatus;
    error?: (string | null);
    payload?: ({
    [key: string]: unknown;
} | null);
    payload_locked?: boolean;
    payload_locked_at?: (string | null);
    payload_submission?: ({
    [key: string]: unknown;
} | null);
    created_time: string;
    updated_time: string;
};

/**
 * 调参对话消息角色。
 */
export type ChatTuneMessageRole = 'user' | 'assistant' | 'system';

/**
 * 重试失败轮次后的响应。
 *
 * 复用原 ``turn_id`` 原地重跑，前端可继续订阅同一个 ``/stream`` 端点。
 */
export type ChatTuneRetryResponse = {
    session_id: string;
    turn_id: string;
    assistant_message: ChatTuneMessageItem;
};

/**
 * 会话详情，含分页历史消息。
 */
export type ChatTuneSessionDetailResponse = {
    session: ChatTuneSessionItem;
    messages?: Array<ChatTuneMessageItem>;
    /**
     * 是否还有更早的历史消息未返回；为 True 时前端可用最早一条消息的 id 作为 before 游标继续翻页
     */
    has_more?: boolean;
};

/**
 * 调参会话的响应模型。
 */
export type ChatTuneSessionItem = {
    id: string;
    user_id: string;
    task_id: string;
    active_turn_id?: (string | null);
    latest_config?: {
        [key: string]: unknown;
    };
    gathering_status?: ChatTuneStageStatus;
    build_status?: ChatTuneStageStatus;
    review_status?: ChatTuneStageStatus;
    active_stage?: ChatTuneActiveStage;
    created_time: string;
    updated_time: string;
};

/**
 * 调参会话中某个阶段的生命周期状态。
 *
 * 每个阶段（gathering/build/review）维护一份独立的状态：协程开始执行
 * 置 ``RUNNING``，对应成功事件到达置 ``COMPLETED``，进入异常处理置
 * ``FAILED``。取消不更新阶段状态——保留最后一次显式置位的值。
 */
export type ChatTuneStageStatus = 'not_started' | 'running' | 'completed' | 'failed';

/**
 * 停止当前正在生成的轮次后的响应。
 */
export type ChatTuneStopResponse = {
    session_id: string;
    turn_id: string;
    status: ChatTuneTurnStatus;
    message: string;
};

/**
 * 重试失败/已停止轮次的请求体。
 *
 * 可选地覆盖 Provider/Model；为空则走用户默认报告模型，再回退到任务的
 * 第一个 Provider，与历史行为保持一致。
 */
export type ChatTuneTurnRetryRequest = {
    /**
     * LLM Provider ID；支持空/'default'/'mock'/真实 UUID
     */
    provider_id?: (string | null);
    /**
     * 覆盖 Provider 默认模型的模型名
     */
    model_name?: (string | null);
};

/**
 * 触发新一轮调参的请求体。
 *
 * 支持两种输入来源（可叠加）：
 * - 普通文字消息：仅填 ``content``。
 * - 响应上一轮的表单：填 ``respond_to_message_id`` + ``submission``，
 * ``content`` 可省略；后端会原子地完成"锁定旧消息 + 触发新一轮"。
 */
export type ChatTuneTurnStartRequest = {
    /**
     * 用户文字内容；与表单提交可叠加，但两者至少要有其一
     */
    content?: (string | null);
    /**
     * 若本轮是对某条 assistant 消息的表单回复，填该消息 ID
     */
    respond_to_message_id?: (string | null);
    /**
     * 表单填写值；与 ``respond_to_message_id`` 必须同时出现或同时缺省
     */
    submission?: ({
    [key: string]: unknown;
} | null);
    /**
     * LLM Provider ID；支持空/'default'/'mock'/真实 UUID
     */
    provider_id?: (string | null);
    /**
     * 覆盖 Provider 默认模型的模型名
     */
    model_name?: (string | null);
    /**
     * 显式指定本轮要执行的阶段（gathering/build/review），用于前端覆盖后端的默认分发；为 None 时由后端按会话状态自动判断。仅 start_turn 接受此参数；retry_turn 不受影响。
     */
    target_stage?: (ChatTuneActiveStage | null);
    /**
     * 本轮对话使用的语言（zh/en），驱动 LLM 回答语言
     */
    language?: 'zh' | 'en';
};

/**
 * 触发新一轮调参生成后的响应。
 */
export type ChatTuneTurnStartResponse = {
    session_id: string;
    turn_id: string;
    user_message: ChatTuneMessageItem;
    assistant_message: ChatTuneMessageItem;
    locked_message?: (ChatTuneMessageItem | null);
};

/**
 * 单轮调参生成状态。
 *
 * 状态机：``GENERATING`` 是唯一非终态，最终单向流转到
 * ``COMPLETED`` / ``FAILED`` / ``CANCELLED`` 之一。
 */
export type ChatTuneTurnStatus = 'generating' | 'completed' | 'failed' | 'cancelled';

/**
 * 调参对话上传目录响应。
 */
export type ChatTuneUploadDataResponse = {
    /**
     * 更新后的消息 payload
     */
    payload: {
        [key: string]: unknown;
    };
};

/**
 * 调参对话上传文件响应。
 */
export type ChatTuneUploadFileResponse = {
    /**
     * 更新后的消息 payload
     */
    payload: {
        [key: string]: unknown;
    };
};

/**
 * 『联系我们』展示模式枚举。
 *
 * 决定该活码是否、以及如何出现在前端「联系我们」面板。
 */
export type ContactDisplay = 'none' | 'landing' | 'direct';

/**
 * Embedding text/code 配置模式。
 */
export type EmbeddingMode = 'shared' | 'split';

/**
 * Embedding 供应商创建请求。
 */
export type EmbeddingProviderCreate = {
    name: string;
    type?: EmbeddingProviderType;
    /**
     * API 密钥（加密存储）
     */
    api_key?: string;
    /**
     * 认证令牌（加密存储）
     */
    auth_token?: string;
    /**
     * Embedding API 基础 URL
     */
    base_url?: (string | null);
    /**
     * text/code 共用或分流
     */
    mode?: EmbeddingMode;
    /**
     * 共用 embedding 模型名称
     */
    model?: string;
    /**
     * Embedding 向量维度
     */
    dim?: number;
    /**
     * 请求超时时间（秒）
     */
    timeout?: number;
    /**
     * 最大并发 embedding 请求数
     */
    embedding_func_max_async?: number;
    /**
     * 文本 embedding 供应商类型
     */
    text_type?: EmbeddingProviderType;
    /**
     * 文本 embedding API 基础 URL
     */
    text_base_url?: (string | null);
    /**
     * 文本 embedding API 密钥
     */
    text_api_key?: string;
    /**
     * 文本 embedding 认证令牌
     */
    text_auth_token?: string;
    /**
     * 文本 embedding 模型名称
     */
    text_model?: string;
    /**
     * 文本 embedding 任务模式
     */
    text_task?: string;
    /**
     * 代码 embedding 供应商类型
     */
    code_type?: EmbeddingProviderType;
    /**
     * 代码 embedding API 基础 URL
     */
    code_base_url?: (string | null);
    /**
     * 代码 embedding API 密钥
     */
    code_api_key?: string;
    /**
     * 代码 embedding 认证令牌
     */
    code_auth_token?: string;
    /**
     * 代码 embedding 模型名称
     */
    code_model?: string;
    /**
     * 代码 embedding 任务模式
     */
    code_task?: string;
    /**
     * 系统内置 embedding 供应商，仅 init_db 可修改
     */
    is_builtin?: boolean;
    /**
     * 对所有用户可见可用
     */
    visible_to_all?: boolean;
};

/**
 * Embedding 供应商响应，凭据不返回明文。
 */
export type EmbeddingProviderResponse = {
    id: string;
    created_time: string;
    updated_time: string;
    user_id: (string | null);
    name: string;
    type: EmbeddingProviderType;
    api_key: string;
    auth_token: string;
    base_url: (string | null);
    mode: EmbeddingMode;
    model: string;
    dim: number;
    timeout: number;
    embedding_func_max_async: number;
    text_type: EmbeddingProviderType;
    text_base_url: (string | null);
    text_api_key: string;
    text_auth_token: string;
    text_model: string;
    text_task: string;
    code_type: EmbeddingProviderType;
    code_base_url: (string | null);
    code_api_key: string;
    code_auth_token: string;
    code_model: string;
    code_task: string;
    is_builtin: boolean;
    visible_to_all: boolean;
};

/**
 * Embedding 供应商类型枚举。
 */
export type EmbeddingProviderType = 'openai' | 'jina' | 'openai_compatible' | 'mock' | 'local';

/**
 * Embedding 供应商更新请求（所有字段均可选）。
 */
export type EmbeddingProviderUpdate = {
    name?: (string | null);
    type?: (EmbeddingProviderType | null);
    api_key?: (string | null);
    auth_token?: (string | null);
    base_url?: (string | null);
    mode?: (EmbeddingMode | null);
    model?: (string | null);
    dim?: (number | null);
    timeout?: (number | null);
    embedding_func_max_async?: (number | null);
    text_type?: (EmbeddingProviderType | null);
    text_base_url?: (string | null);
    text_api_key?: (string | null);
    text_auth_token?: (string | null);
    text_model?: (string | null);
    text_task?: (string | null);
    code_type?: (EmbeddingProviderType | null);
    code_base_url?: (string | null);
    code_api_key?: (string | null);
    code_auth_token?: (string | null);
    code_model?: (string | null);
    code_task?: (string | null);
};

/**
 * 单个示例模板下的配置文件。
 */
export type ExampleTemplateConfigItem = {
    /**
     * 配置文件名
     */
    name: string;
    /**
     * 配置文件英文简介，用于前端提示
     */
    description_en?: (string | null);
    /**
     * 配置文件中文简介，用于前端提示
     */
    description_zh?: (string | null);
};

/**
 * 单个示例模板。
 */
export type ExampleTemplateItem = {
    /**
     * 模板文件夹名称
     */
    name: string;
    /**
     * 配置文件列表，每项包含文件名与可选的中英文简介
     */
    configs?: Array<ExampleTemplateConfigItem>;
};

/**
 * 示例模板列表响应。
 */
export type ExampleTemplateListResponse = {
    /**
     * 可用的示例模板列表
     */
    templates?: Array<ExampleTemplateItem>;
};

/**
 * 反馈管理员响应模型（包含内部信息）。
 */
export type FeedbackAdmin = {
    /**
     * 反馈类型
     */
    type?: FeedbackType;
    /**
     * 反馈标题
     */
    title: string;
    /**
     * 反馈详细内容
     */
    content: string;
    /**
     * 联系邮箱（可选）
     */
    contact_email?: (string | null);
    /**
     * 联系电话（可选）
     */
    contact_phone?: (string | null);
    /**
     * 浏览器信息
     */
    browser_info?: (string | null);
    /**
     * 反馈页面 URL
     */
    page_url?: (string | null);
    /**
     * 截图 URL（可选）
     */
    screenshot_url?: (string | null);
    /**
     * 附件 URL 列表（JSON 格式）
     */
    attachments?: (string | null);
    id: string;
    user_id: (string | null);
    status: FeedbackStatus;
    priority: FeedbackPriority;
    admin_reply: (string | null);
    resolved_time: (string | null);
    tags: (string | null);
    created_time: string;
    updated_time: string;
    /**
     * 提交人邮箱
     */
    user_email?: (string | null);
    /**
     * 提交人姓名
     */
    user_full_name?: (string | null);
    admin_id: (string | null);
    internal_notes: (string | null);
};

/**
 * 创建反馈请求模型。
 */
export type FeedbackCreate = {
    /**
     * 反馈类型
     */
    type?: FeedbackType;
    /**
     * 反馈标题
     */
    title: string;
    /**
     * 反馈详细内容
     */
    content: string;
    /**
     * 联系邮箱（可选）
     */
    contact_email?: (string | null);
    /**
     * 联系电话（可选）
     */
    contact_phone?: (string | null);
    /**
     * 浏览器信息
     */
    browser_info?: (string | null);
    /**
     * 反馈页面 URL
     */
    page_url?: (string | null);
    /**
     * 截图 URL（可选）
     */
    screenshot_url?: (string | null);
    /**
     * 附件 URL 列表（JSON 格式）
     */
    attachments?: (string | null);
};

/**
 * 反馈优先级枚举。
 */
export type FeedbackPriority = 'low' | 'medium' | 'high' | 'urgent';

/**
 * 反馈公开响应模型（用户视图）。
 */
export type FeedbackPublic = {
    /**
     * 反馈类型
     */
    type?: FeedbackType;
    /**
     * 反馈标题
     */
    title: string;
    /**
     * 反馈详细内容
     */
    content: string;
    /**
     * 联系邮箱（可选）
     */
    contact_email?: (string | null);
    /**
     * 联系电话（可选）
     */
    contact_phone?: (string | null);
    /**
     * 浏览器信息
     */
    browser_info?: (string | null);
    /**
     * 反馈页面 URL
     */
    page_url?: (string | null);
    /**
     * 截图 URL（可选）
     */
    screenshot_url?: (string | null);
    /**
     * 附件 URL 列表（JSON 格式）
     */
    attachments?: (string | null);
    id: string;
    user_id: (string | null);
    status: FeedbackStatus;
    priority: FeedbackPriority;
    admin_reply: (string | null);
    resolved_time: (string | null);
    tags: (string | null);
    created_time: string;
    updated_time: string;
    /**
     * 提交人邮箱
     */
    user_email?: (string | null);
    /**
     * 提交人姓名
     */
    user_full_name?: (string | null);
};

/**
 * 反馈列表响应模型。
 */
export type FeedbacksPublic = {
    items: Array<FeedbackPublic>;
    total: number;
    skip: number;
    limit: number;
};

/**
 * 反馈统计信息模型。
 */
export type FeedbackStatistics = {
    /**
     * 总反馈数
     */
    total: number;
    /**
     * 待处理数
     */
    pending: number;
    /**
     * 处理中数
     */
    in_progress: number;
    /**
     * 已解决数
     */
    resolved: number;
    /**
     * 已关闭数
     */
    closed: number;
    /**
     * 已拒绝数
     */
    rejected: number;
    /**
     * 按类型统计
     */
    by_type: {
        [key: string]: (number);
    };
    /**
     * 按优先级统计
     */
    by_priority: {
        [key: string]: (number);
    };
};

/**
 * 反馈状态枚举。
 */
export type FeedbackStatus = 'pending' | 'in_progress' | 'resolved' | 'closed' | 'rejected';

/**
 * 反馈类型枚举。
 */
export type FeedbackType = 'bug' | 'feature' | 'improvement' | 'question' | 'other';

/**
 * 更新反馈请求模型（管理员使用）。
 */
export type FeedbackUpdate = {
    status?: (FeedbackStatus | null);
    priority?: (FeedbackPriority | null);
    admin_reply?: (string | null);
    tags?: (string | null);
    internal_notes?: (string | null);
};

/**
 * 文件内容响应。
 */
export type FileContentResponse = {
    file_path: string;
    content: string;
};

/**
 * 文件创建请求。
 */
export type FileCreateRequest = {
    /**
     * 用户已选择的路径：文件路径(如 'a/b/c.txt')、目录路径(如 'a/b/c/')、或为空/null表示根目录
     */
    path?: (string | null);
};

/**
 * 文件创建响应。
 */
export type FileCreateResponse = {
    /**
     * 已创建文件的相对路径
     */
    file_path: string;
};

/**
 * 文件重命名请求。
 */
export type FileRenameRequest = {
    /**
     * 原文件相对路径
     */
    old_path: string;
    /**
     * 新文件相对路径
     */
    new_path: string;
};

/**
 * 文件树节点。
 */
export type FileTreeNode = {
    /**
     * 文件或目录名称
     */
    name: string;
    /**
     * 相对路径
     */
    path: string;
    /**
     * 节点类型: file 或 directory
     */
    type: string;
    children?: (Array<FileTreeNode> | null);
};

/**
 * 文件目录树响应。
 */
export type FileTreeResponse = {
    tree: Array<FileTreeNode>;
};

/**
 * 文件修改请求。
 */
export type FileUpdateRequest = {
    /**
     * 文件相对路径
     */
    file_path: string;
    /**
     * 文件新内容
     */
    content: string;
};

/**
 * 文件夹创建请求。
 */
export type FolderCreateRequest = {
    /**
     * 父目录相对路径，必须指向已有目录（不支持创建顶级文件夹）
     */
    path?: (string | null);
    /**
     * 新文件夹名称，为空时自动生成（new_folder、new_folder_1...）
     */
    name?: (string | null);
};

/**
 * 文件夹创建响应。
 */
export type FolderCreateResponse = {
    /**
     * 已创建文件夹的相对路径
     */
    folder_path: string;
};

/**
 * 文件夹重命名请求。
 */
export type FolderRenameRequest = {
    /**
     * 原文件夹相对路径
     */
    old_path: string;
    /**
     * 新文件夹相对路径
     */
    new_path: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * LiteLLM 用户额度列表项。
 */
export type LiteLLMUserQuotaItem = {
    user_id?: (string | null);
    user_email?: (string | null);
    full_name?: (string | null);
    user_alias?: (string | null);
    spend?: (number | null);
    budget?: (number | null);
    remaining?: (number | null);
    teams?: Array<(string)>;
    created_at?: (string | null);
    updated_at?: (string | null);
};

/**
 * LiteLLM 用户额度列表响应。
 */
export type LiteLLMUserQuotaListResponse = {
    available?: boolean;
    items?: Array<LiteLLMUserQuotaItem>;
    total?: number;
    message?: string;
};

/**
 * 『联系我们』活码公开信息（免鉴权）。
 *
 * 仅暴露展示所需的最小字段，供前端拉取并渲染二维码与引导文案。
 * ``image_url`` 已由后端按展示模式解析：landing 为永久码 PNG，direct 为真实图片。
 */
export type LiveCodeContactInfo = {
    /**
     * 公开短码
     */
    slug: string;
    /**
     * 展示标题
     */
    landing_title?: (string | null);
    /**
     * 引导文案
     */
    landing_tip?: (string | null);
    /**
     * 展示模式：landing 永久码 / direct 真实图片
     */
    display: ContactDisplay;
    /**
     * 最终展示图片的公开 URL（可直接用于 img）；direct 无有效真实码时为空串
     */
    image_url: string;
};

/**
 * 创建活码请求体。
 */
export type LiveCodeCreate = {
    /**
     * 活码名称
     */
    name: string;
    /**
     * 备注说明
     */
    description?: (string | null);
    /**
     * 真实群码切换策略
     */
    strategy?: LiveCodeStrategy;
    /**
     * 落地页主标题
     */
    landing_title?: (string | null);
    /**
     * 落地页引导文案
     */
    landing_tip?: (string | null);
};

/**
 * 活码详情响应模型，附带真实群码列表。
 */
export type LiveCodeDetail = {
    id: string;
    slug: string;
    name: string;
    description: (string | null);
    strategy: LiveCodeStrategy;
    landing_title: (string | null);
    landing_tip: (string | null);
    is_active: boolean;
    /**
     * 『联系我们』展示模式：none/landing/direct
     */
    contact_display: ContactDisplay;
    total_scans: number;
    created_time: string;
    updated_time: string;
    /**
     * 对外永久落地页 URL（永久二维码所编码的内容）
     */
    public_url: string;
    /**
     * 下载永久二维码 PNG 的相对 API 路径
     */
    qrcode_url: string;
    /**
     * 真实群码总数
     */
    target_count: number;
    /**
     * 当前有效的真实群码数量
     */
    valid_target_count: number;
    /**
     * 创建者邮箱
     */
    creator_email?: (string | null);
    /**
     * 创建者姓名
     */
    creator_name?: (string | null);
    targets?: Array<TargetPublic>;
};

/**
 * 活码响应模型（列表/详情公共部分）。
 */
export type LiveCodePublic = {
    id: string;
    slug: string;
    name: string;
    description: (string | null);
    strategy: LiveCodeStrategy;
    landing_title: (string | null);
    landing_tip: (string | null);
    is_active: boolean;
    /**
     * 『联系我们』展示模式：none/landing/direct
     */
    contact_display: ContactDisplay;
    total_scans: number;
    created_time: string;
    updated_time: string;
    /**
     * 对外永久落地页 URL（永久二维码所编码的内容）
     */
    public_url: string;
    /**
     * 下载永久二维码 PNG 的相对 API 路径
     */
    qrcode_url: string;
    /**
     * 真实群码总数
     */
    target_count: number;
    /**
     * 当前有效的真实群码数量
     */
    valid_target_count: number;
    /**
     * 创建者邮箱
     */
    creator_email?: (string | null);
    /**
     * 创建者姓名
     */
    creator_name?: (string | null);
};

/**
 * 真实群码的切换策略枚举。
 */
export type LiveCodeStrategy = 'sequential' | 'round_robin' | 'random';

/**
 * 更新活码请求体，所有字段可选。
 */
export type LiveCodeUpdate = {
    name?: (string | null);
    description?: (string | null);
    strategy?: (LiveCodeStrategy | null);
    landing_title?: (string | null);
    landing_tip?: (string | null);
    is_active?: (boolean | null);
    contact_display?: (ContactDisplay | null);
};

/**
 * 通用消息响应模型，用于返回简单的文本提示信息。
 */
export type Message = {
    message?: string;
};

/**
 * 密码重置请求模型，包含重置令牌和新密码。
 */
export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * Embedding 供应商分页响应。
 */
export type PaginatedEmbeddingProviderResponse = {
    items: Array<EmbeddingProviderResponse>;
    total: number;
    skip: number;
    limit: number;
};

/**
 * 活码分页列表响应模型。
 */
export type PaginatedLiveCode = {
    items: Array<LiveCodePublic>;
    total: number;
    skip: number;
    limit: number;
};

/**
 * 项目分页响应。
 */
export type PaginatedProjectResponse = {
    items: Array<ProjectResponse>;
    total: number;
    skip: number;
    limit: number;
};

/**
 * 供应商分页响应。
 */
export type PaginatedProviderResponse = {
    items: Array<ProviderResponse>;
    total: number;
    skip: number;
    limit: number;
};

/**
 * 任务分页响应。
 */
export type PaginatedTaskResponse = {
    items: Array<TaskResponse>;
    total: number;
    skip: number;
    limit: number;
};

/**
 * 权限基础 Schema，定义权限的公共字段。
 */
export type PermissionBase = {
    name?: string;
    description?: string;
    /**
     * 权限类型，备用
     */
    type?: string;
};

/**
 * 隐私协议内容响应。
 */
export type PrivacyPolicyContent = {
    title: string;
    content: string;
    version: string;
    updated_at: string;
};

/**
 * 项目创建请求。
 */
export type ProjectCreate = {
    name: string;
    description?: (string | null);
    icon?: (string | null);
};

/**
 * 项目基础响应。
 */
export type ProjectResponse = {
    id: string;
    created_time: string;
    updated_time: string;
    name: string;
    description: (string | null);
    icon: (string | null);
    user_id: string;
};

/**
 * 项目更新请求（所有字段均可选）。
 */
export type ProjectUpdate = {
    name?: (string | null);
    description?: (string | null);
    icon?: (string | null);
};

/**
 * 供应商创建请求。
 */
export type ProviderCreate = {
    name: string;
    type?: ProviderType;
    /**
     * API 密钥（加密存储）
     */
    api_key?: string;
    /**
     * 认证令牌（如 Anthropic，加密存储）
     */
    auth_token?: string;
    /**
     * 自定义 API 基础 URL
     */
    base_url?: (string | null);
    /**
     * 使用的模型名称，支持多个，使用;分割
     */
    model?: string;
    /**
     * 采样温度
     */
    temperature?: number;
    /**
     * 最大生成 token 数
     */
    max_tokens?: number;
    /**
     * 请求超时时间（秒）
     */
    timeout?: number;
    /**
     * 最大重试次数
     */
    max_retries?: number;
    /**
     * 系统内置供应商，仅 init_db 可修改
     */
    is_builtin?: boolean;
    /**
     * 对所有用户可见可用
     */
    visible_to_all?: boolean;
};

/**
 * 供应商响应。
 *
 * 所有供应商的 api_key/auth_token 均不返回明文：已设置的凭据替换为占位符
 * ``sk-***``，未设置的返回空串，使前端既能区分"是否已配置"，又无法读到真实
 * 凭据。内置供应商（is_builtin=True）额外屏蔽 base_url（含网关地址/令牌）；
 * 用户自有供应商的 base_url 非敏感，原样返回以便编辑。
 */
export type ProviderResponse = {
    id: string;
    created_time: string;
    updated_time: string;
    name: string;
    type: ProviderType;
    api_key: string;
    auth_token: string;
    base_url: (string | null);
    model: string;
    temperature: number;
    max_tokens: number;
    timeout: number;
    max_retries: number;
    is_builtin?: boolean;
    visible_to_all?: boolean;
    user_id?: (string | null);
};

/**
 * 已存储供应商的联通性测试请求。
 *
 * 通过供应商 ID 复用数据库中保存的凭据（适用于内置供应商，
 * 前端无法获取明文 api_key/base_url），仅需指定要测试的模型名称。
 *
 * 编辑态下前端可携带表单当前值作为「字段级覆盖」：某字段非空则用该值，
 * 为空则回退到数据库中保存的真实值，从而支持「表单新值 + 库中旧值」混合测试。
 * 出于安全考虑，覆盖仅对用户自有供应商生效；内置供应商一律忽略覆盖、只用
 * 库中凭据，避免内置网关密钥被诱导发往任意 base_url。
 */
export type ProviderTestByIdRequest = {
    model: string;
    prompt?: string;
    api_key?: (string | null);
    auth_token?: (string | null);
    base_url?: (string | null);
};

/**
 * 供应商联通性测试请求。
 */
export type ProviderTestRequest = {
    type?: ProviderType;
    model: string;
    api_key?: string;
    auth_token?: string;
    base_url?: (string | null);
    prompt?: string;
};

/**
 * 供应商联通性测试响应。
 */
export type ProviderTestResponse = {
    success: boolean;
    message: string;
    data?: unknown;
};

/**
 * LLM 供应商类型枚举。
 */
export type ProviderType = 'openai' | 'anthropic' | 'openai_compatible' | 'mock';

/**
 * 供应商更新请求（所有字段均可选）。
 */
export type ProviderUpdate = {
    name?: (string | null);
    type?: (ProviderType | null);
    api_key?: (string | null);
    auth_token?: (string | null);
    base_url?: (string | null);
    model?: (string | null);
    temperature?: (number | null);
    max_tokens?: (number | null);
    timeout?: (number | null);
    max_retries?: (number | null);
};

/**
 * 刷新令牌请求体。
 */
export type RefreshAccessToken = {
    refresh_token: string;
};

/**
 * 获取指定报告详情的响应体。
 */
export type ReportDetailResponse = {
    task_id: string;
    report_type: ReportType;
    report?: (ReportEntry | null);
};

/**
 * 存储于 ``task.reports`` 字典中的单条报告条目。
 *
 * Attributes:
 * status: 当前生成状态。
 * content: 报告正文内容（成功时存在）。
 * created_at: 创建时间。
 * updated_at: 最近一次更新时间。
 * error: 错误信息（失败时存在）。
 * provider_model: 实际使用的 LLM 模型名称。
 * params: 生成报告时使用的参数快照。
 */
export type ReportEntry = {
    status: ReportStatus;
    content?: (string | null);
    created_at: string;
    updated_at: string;
    error?: (string | null);
    provider_model?: (string | null);
    params?: {
        [key: string]: unknown;
    };
};

/**
 * 报告生成请求体。
 *
 * 根据 ``report_type`` 不同，需要传入对应的额外参数：
 *
 * * ``NODE_COMPARISON`` / ``CHAIN_ANALYSIS``：必须提供至少 2 个 ``node_ids``。
 * * ``CHAMPION_BIRTH``：必须提供 ``best_node_id``。
 */
export type ReportGenerateRequest = {
    /**
     * 待生成的报告类型
     */
    report_type: ReportType;
    /**
     * 输出语言：'zh' 表示中文，'en' 表示英文
     */
    language?: 'zh' | 'en';
    /**
     * LLM Provider ID；支持传空字符串/null（使用用户默认）、'default'（使用用户默认）、'mock'（mock模式）、真实的供应商UUID
     */
    provider_id?: (string | null);
    /**
     * 指定使用的模型名称；未提供时使用 Provider 默认模型
     */
    model_name?: (string | null);
    /**
     * 自定义 Prompt 模板；未提供时使用内置默认模板
     */
    prompt_template?: (string | null);
    /**
     * 节点 ID 列表，用于 node_comparison 与 chain_analysis 报告
     */
    node_ids?: (Array<(string)> | null);
    /**
     * 最佳节点 ID，用于 champion_birth 报告
     */
    best_node_id?: (string | null);
};

/**
 * 触发报告生成后的响应体。
 */
export type ReportGenerateResponse = {
    task_id: string;
    report_type: ReportType;
    status: ReportStatus;
    message: string;
};

/**
 * 报告生成状态枚举。
 *
 * Attributes:
 * GENERATING: 生成中。
 * COMPLETED: 生成完成。
 * FAILED: 生成失败。
 * CANCELLED: 已取消。
 */
export type ReportStatus = 'generating' | 'completed' | 'failed' | 'cancelled';

/**
 * 停止报告生成后的响应体。
 */
export type ReportStopResponse = {
    task_id: string;
    report_type: ReportType;
    status: ReportStatus;
    message: string;
};

/**
 * 单个报告类型的 Prompt 模板信息。
 */
export type ReportTemplateItem = {
    /**
     * User prompt 模板，变量用 {variable_name} 标记
     */
    user_prompt_template: string;
    /**
     * 模板中可用的变量名列表
     */
    variables: Array<(string)>;
};

/**
 * 所有报告类型的 Prompt 模板响应体。
 */
export type ReportTemplatesResponse = {
    templates: {
        [key: string]: ReportTemplateItem;
    };
};

/**
 * 报告类型枚举。
 *
 * Attributes:
 * TECH_CHANGE: 技术演化变更报告。
 * NODE_COMPARISON: 节点对比报告。
 * CHAIN_ANALYSIS: 演化链路分析报告。
 * CHAMPION_BIRTH: 冠军算法诞生报告。
 */
export type ReportType = 'tech_change' | 'node_comparison' | 'chain_analysis' | 'champion_birth';

/**
 * 重新发送验证码请求。
 */
export type ResendVerifyCodeRequest = {
    email: string;
};

/**
 * 重新发送验证码响应，当 SKIP_EMAIL_VERIFICATION 开启时额外返回验证码。
 */
export type ResendVerifyCodeResponse = {
    message?: string;
    verify_code?: (string | null);
};

/**
 * 结果渲染生成请求体。
 */
export type ResultRenderGenerateRequest = {
    /**
     * 结果渲染类型
     */
    result_type: ResultRenderType;
    /**
     * 输出语言：'zh' 表示中文，'en' 表示英文
     */
    language?: 'zh' | 'en';
    /**
     * 主题：'light' 浅色，'dark' 深色
     */
    theme?: 'light' | 'dark';
    /**
     * 是否强制重新生成，忽略已有缓存
     */
    force?: boolean;
};

/**
 * 主题：'light' 浅色，'dark' 深色
 */
export type theme = 'light' | 'dark';

/**
 * 结果渲染生成响应体。
 */
export type ResultRenderGenerateResponse = {
    task_id: string;
    result_type: ResultRenderType;
    status: ResultRenderStatus;
    message: string;
    /**
     * 机器可读错误码
     */
    error_code?: (string | null);
    /**
     * 结果渲染数据
     */
    data?: unknown;
};

/**
 * 结果渲染状态枚举。
 */
export type ResultRenderStatus = 'completed' | 'failed';

/**
 * 结果渲染类型枚举。
 */
export type ResultRenderType = 'trajectory';

/**
 * 设置根任务当前选中的子任务版本。
 */
export type SetActiveChildRequest = {
    /**
     * 子任务 ID；传 null 清除选中，读取时默认回退为指向自身
     */
    child_id?: (string | null);
};

/**
 * 任务输入数据存储用量。
 */
export type StorageUsage = {
    /**
     * 已使用空间（字节）
     */
    used_bytes: number;
    /**
     * 空间上限（字节）
     */
    limit_bytes: number;
    /**
     * 已使用空间（MB，保留两位小数）
     */
    used_mb: number;
    /**
     * 空间上限（MB）
     */
    limit_mb: number;
};

/**
 * 真实群码响应模型（管理端视图）。
 */
export type TargetPublic = {
    id: string;
    label: (string | null);
    expires_at: (string | null);
    scan_limit: (number | null);
    scan_count: number;
    is_enabled: boolean;
    sort_order: number;
    created_time: string;
    /**
     * 后台预览图片的相对 API 路径
     */
    image_url: string;
    /**
     * 当前是否可用（启用且未过期未满员）
     */
    is_valid: boolean;
    /**
     * 人类可读状态：valid / disabled / expired / full
     */
    status: string;
};

/**
 * 更新真实群码请求体，所有字段可选。
 */
export type TargetUpdate = {
    label?: (string | null);
    expires_at?: (string | null);
    scan_limit?: (number | null);
    is_enabled?: (boolean | null);
    sort_order?: (number | null);
};

/**
 * 任务复制请求。
 */
export type TaskCopyRequest = {
    /**
     * 是否作为子任务复制
     */
    is_child?: boolean;
};

/**
 * 任务创建请求。input_args 为空时自动填充 AppConfig 默认值。
 */
export type TaskCreate = {
    name: string;
    description?: (string | null);
    project_id: string;
    input_args?: ({
    [key: string]: unknown;
} | null);
    /**
     * 示例模板名称，选择后自动填充数据和参数
     */
    template_name?: (string | null);
    /**
     * 模板中的配置文件名，默认为 config.yaml
     */
    config_name?: (string | null);
    /**
     * 语言参数（zh/en），影响初始调参消息语言
     */
    language?: string;
    /**
     * 是否由 AI 构建
     */
    ai_built?: boolean;
};

/**
 * 任务日志游标分页响应。
 */
export type TaskLogsResponse = {
    task_id: string;
    /**
     * 日志来源: db 或 redis
     */
    source: string;
    /**
     * 日志条目列表（按时间正序）
     */
    entries?: Array<{
        [key: string]: unknown;
    }>;
    /**
     * 下一页游标，null 表示没有更多数据
     */
    next_cursor?: (string | null);
    /**
     * 是否还有更早的日志
     */
    has_more?: boolean;
};

/**
 * 任务基础响应。
 */
export type TaskResponse = {
    id: string;
    created_time: string;
    updated_time: string;
    project_id: string;
    name: string;
    description: (string | null);
    status: TaskStatus;
    input_args: {
        [key: string]: unknown;
    };
    celery_task_id?: (string | null);
    input_data_path?: (string | null);
    reports?: ({
    [key: string]: unknown;
} | null);
    group_id?: (string | null);
    parent_id?: (string | null);
    tag?: (string | null);
    active_child_id?: (string | null);
    ai_built?: boolean;
    ai_build_started?: boolean;
    /**
     * active_child_id 指向任务的状态；为空或指向自身时等于本任务自身的 status
     */
    active_status?: (TaskStatus | null);
    storage_usage?: (StorageUsage | null);
    children_count?: (number | null);
};

/**
 * 任务 Celery 执行结果响应。
 */
export type TaskResultResponse = {
    task_id: string;
    celery_task_id?: (string | null);
    celery_status: string;
    status: TaskStatus;
    result?: ({
    [key: string]: unknown;
} | null);
    error?: (string | null);
};

/**
 * 任务运行提交响应。
 */
export type TaskRunResponse = {
    task_id: string;
    celery_task_id: string;
    status: TaskStatus;
};

export type tasks_upload_task_data = {
    /**
     * 上传的文件列表
     */
    files: Array<((Blob | File))>;
};

/**
 * 任务基本统计信息响应。
 */
export type TaskStatsResponse = {
    task_id: string;
    /**
     * 解的个数
     */
    solution_count: number;
    /**
     * 解的平均分（无解时为 None）
     */
    avg_score?: (number | null);
    /**
     * 解的最高分（无解时为 None）
     */
    max_score?: (number | null);
    /**
     * 任务参数 JSON
     */
    input_args?: {
        [key: string]: unknown;
    };
    /**
     * 任务创建时间
     */
    created_time: string;
    /**
     * 任务最后修改时间
     */
    updated_time: string;
};

/**
 * 任务状态枚举。
 */
export type TaskStatus = 'uninitialized' | 'pending' | 'running' | 'completed' | 'failed';

/**
 * 任务标签更新请求。
 */
export type TaskTagUpdate = {
    /**
     * 任务标签
     */
    tag?: (string | null);
};

/**
 * 任务树节点，包含常用信息，不包含 logs 和 result 等大字段。
 */
export type TaskTreeItem = {
    id: string;
    name: string;
    description?: (string | null);
    status: TaskStatus;
    created_time: string;
    updated_time: string;
    project_id: string;
    group_id?: (string | null);
    parent_id?: (string | null);
    tag?: (string | null);
    active_child_id?: (string | null);
    celery_task_id?: (string | null);
    input_data_path?: (string | null);
};

/**
 * 任务树响应。
 */
export type TaskTreeResponse = {
    root: TaskTreeItem;
    children: Array<TaskTreeItem>;
};

/**
 * 任务更新请求（所有字段均可选）。
 */
export type TaskUpdate = {
    name?: (string | null);
    description?: (string | null);
    input_args?: ({
    [key: string]: unknown;
} | null);
};

/**
 * JWT 令牌响应模型，包含访问令牌和刷新令牌。
 */
export type Token = {
    access_token: string;
    refresh_token: string;
    token_type?: string;
};

/**
 * 用户修改密码请求。
 */
export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

/**
 * 用户创建请求（管理员创建用户）。
 */
export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    email_verified?: boolean;
    full_name?: (string | null);
    privacy_policy_accepted?: boolean;
    privacy_policy_accepted_at?: (string | null);
    password: string;
};

/**
 * 用户默认模型配置响应。
 */
export type UserDefaultModelResponse = {
    id: string;
    created_time: string;
    updated_time: string;
    user_id: string;
    planner_provider_id: (string | null);
    planner_provider_name?: (string | null);
    planner_model_name: (string | null);
    coder_provider_id: (string | null);
    coder_provider_name?: (string | null);
    coder_model_name: (string | null);
    report_provider_id: (string | null);
    report_provider_name?: (string | null);
    report_model_name: (string | null);
    other_provider_id: (string | null);
    other_provider_name?: (string | null);
    other_model_name: (string | null);
    embedding_enabled: boolean;
    embedding_provider_id: (string | null);
    embedding_provider_name?: (string | null);
};

/**
 * 用户默认模型配置更新请求（所有字段均可选）。
 */
export type UserDefaultModelUpdate = {
    planner_provider_id?: (string | null);
    planner_model_name?: (string | null);
    coder_provider_id?: (string | null);
    coder_model_name?: (string | null);
    report_provider_id?: (string | null);
    report_model_name?: (string | null);
    other_provider_id?: (string | null);
    other_model_name?: (string | null);
    embedding_enabled?: (boolean | null);
    embedding_provider_id?: (string | null);
};

/**
 * 用户公开信息响应（隐藏密码等敏感字段）。
 */
export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    email_verified?: boolean;
    full_name?: (string | null);
    privacy_policy_accepted?: boolean;
    privacy_policy_accepted_at?: (string | null);
    id: string;
    created_at?: (string | null);
};

/**
 * 用户自注册请求。
 */
export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
    privacy_policy_accepted?: boolean;
};

/**
 * 注册响应，当 SKIP_EMAIL_VERIFICATION 开启时额外返回验证码。
 */
export type UserRegisterResponse = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    email_verified?: boolean;
    full_name?: (string | null);
    privacy_policy_accepted?: boolean;
    privacy_policy_accepted_at?: (string | null);
    id: string;
    created_at?: (string | null);
    verify_code?: (string | null);
};

/**
 * 用户列表响应，包含分页总数。
 */
export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

/**
 * 用户更新请求（管理员更新用户）。
 */
export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    email_verified?: boolean;
    full_name?: (string | null);
    privacy_policy_accepted?: boolean;
    privacy_policy_accepted_at?: (string | null);
    password?: (string | null);
};

/**
 * 用户自行更新个人信息请求。
 */
export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

/**
 * 邮箱验证码校验请求。
 */
export type VerifyEmailRequest = {
    email: string;
    code: string;
};

export type AdminAnalyticsGetAdminAnalyticsOverviewData = {
    range?: string;
};

export type AdminAnalyticsGetAdminAnalyticsOverviewResponse = ({
    [key: string]: unknown;
});

export type AdminAnalyticsGetAdminOperationsSummaryResponse = ({
    [key: string]: unknown;
});

export type AdminAnalyticsGetAdminOperationsTasksResponse = ({
    [key: string]: unknown;
});

export type AdminAnalyticsGetAdminOperationsFeedbackResponse = ({
    [key: string]: unknown;
});

export type AdminAnalyticsGetAdminOperationsLitellmResponse = ({
    [key: string]: unknown;
});

export type AdminAnalyticsGetAdminVisitorsPlausibleData = {
    range?: string;
};

export type AdminAnalyticsGetAdminVisitorsPlausibleResponse = ({
    [key: string]: unknown;
});

export type AdminAnalyticsGetAdminVisitorsGithubResponse = ({
    [key: string]: unknown;
});

export type FeedbackCreateFeedbackData = {
    requestBody: FeedbackCreate;
};

export type FeedbackCreateFeedbackResponse = (FeedbackPublic);

export type FeedbackListFeedbacksData = {
    /**
     * 单页最大返回数量
     */
    limit?: number;
    /**
     * 按优先级过滤
     */
    priority?: (FeedbackPriority | null);
    /**
     * 跳过的记录数
     */
    skip?: number;
    /**
     * 按状态过滤
     */
    status?: (FeedbackStatus | null);
    /**
     * 按类型过滤
     */
    type?: (FeedbackType | null);
};

export type FeedbackListFeedbacksResponse = (FeedbacksPublic);

export type FeedbackGetFeedbackStatisticsResponse = (FeedbackStatistics);

export type FeedbackGetFeedbackData = {
    feedbackId: string;
};

export type FeedbackGetFeedbackResponse = (FeedbackAdmin);

export type FeedbackUpdateFeedbackData = {
    feedbackId: string;
    requestBody: FeedbackUpdate;
};

export type FeedbackUpdateFeedbackResponse = (FeedbackAdmin);

export type FeedbackDeleteFeedbackData = {
    feedbackId: string;
};

export type FeedbackDeleteFeedbackResponse = (Message);

export type LiveCodesCreateLiveCodeData = {
    requestBody: LiveCodeCreate;
};

export type LiveCodesCreateLiveCodeResponse = (LiveCodeDetail);

export type LiveCodesListLiveCodesData = {
    limit?: number;
    skip?: number;
};

export type LiveCodesListLiveCodesResponse = (PaginatedLiveCode);

export type LiveCodesGetLiveCodeData = {
    liveCodeId: string;
};

export type LiveCodesGetLiveCodeResponse = (LiveCodeDetail);

export type LiveCodesUpdateLiveCodeData = {
    liveCodeId: string;
    requestBody: LiveCodeUpdate;
};

export type LiveCodesUpdateLiveCodeResponse = (LiveCodeDetail);

export type LiveCodesDeleteLiveCodeData = {
    liveCodeId: string;
};

export type LiveCodesDeleteLiveCodeResponse = (Message);

export type LiveCodesAddTargetsData = {
    formData: Body_live_codes_add_targets;
    liveCodeId: string;
};

export type LiveCodesAddTargetsResponse = (LiveCodeDetail);

export type LiveCodesUpdateTargetData = {
    liveCodeId: string;
    requestBody: TargetUpdate;
    targetId: string;
};

export type LiveCodesUpdateTargetResponse = (TargetPublic);

export type LiveCodesDeleteTargetData = {
    liveCodeId: string;
    targetId: string;
};

export type LiveCodesDeleteTargetResponse = (Message);

export type LiveCodesResetTargetScanData = {
    liveCodeId: string;
    targetId: string;
};

export type LiveCodesResetTargetScanResponse = (TargetPublic);

export type LiveQrContactResponse = (Array<LiveCodeContactInfo>);

export type LiveQrTargetImageData = {
    targetId: string;
};

export type LiveQrTargetImageResponse = (unknown);

export type LiveQrLandingData = {
    slug: string;
};

export type LiveQrLandingResponse = (string);

export type LiveQrScanImageData = {
    slug: string;
};

export type LiveQrScanImageResponse = (unknown);

export type LiveQrPublicQrcodeData = {
    slug: string;
};

export type LiveQrPublicQrcodeResponse = (unknown);

export type Llm4AdChatTuneGetSessionData = {
    /**
     * 游标：返回该消息 ID 之前（更早）的消息；缺省时返回最新一页
     */
    before?: (string | null);
    /**
     * 每页条数，默认 50，上限 100
     */
    limit?: number;
    taskId: string;
};

export type Llm4AdChatTuneGetSessionResponse = (ChatTuneSessionDetailResponse);

export type Llm4AdChatTuneResetSessionData = {
    taskId: string;
};

export type Llm4AdChatTuneResetSessionResponse = (ChatTuneSessionItem);

export type Llm4AdChatTuneStartTurnData = {
    requestBody: ChatTuneTurnStartRequest;
    taskId: string;
};

export type Llm4AdChatTuneStartTurnResponse = (ChatTuneTurnStartResponse);

export type Llm4AdChatTuneStopTurnData = {
    taskId: string;
    turnId: string;
};

export type Llm4AdChatTuneStopTurnResponse = (ChatTuneStopResponse);

export type Llm4AdChatTuneRetryTurnData = {
    requestBody?: ChatTuneTurnRetryRequest;
    taskId: string;
    turnId: string;
};

export type Llm4AdChatTuneRetryTurnResponse = (ChatTuneRetryResponse);

export type Llm4AdChatTuneChatTuneUploadFileData = {
    /**
     * payload 卡片 ID
     */
    cardId: string;
    formData: chat_tune_chat_tune_upload_file;
    /**
     * 调参消息 ID
     */
    messageId: string;
    /**
     * 选项在 payload.options 中的索引
     */
    optionIndex: number;
    taskId: string;
};

export type Llm4AdChatTuneChatTuneUploadFileResponse = (ChatTuneUploadFileResponse);

export type Llm4AdChatTuneChatTuneUploadDataData = {
    /**
     * payload 卡片 ID
     */
    cardId: string;
    formData: chat_tune_chat_tune_upload_data;
    /**
     * 调参消息 ID
     */
    messageId: string;
    /**
     * 选项在 payload.options 中的索引
     */
    optionIndex: number;
    taskId: string;
};

export type Llm4AdChatTuneChatTuneUploadDataResponse = (ChatTuneUploadDataResponse);

export type Llm4AdChatTuneStreamTurnData = {
    taskId: string;
    turnId: string;
};

export type Llm4AdChatTuneStreamTurnResponse = (unknown);

export type Llm4AdEmbeddingProvidersCreateEmbeddingProviderData = {
    requestBody: EmbeddingProviderCreate;
};

export type Llm4AdEmbeddingProvidersCreateEmbeddingProviderResponse = (EmbeddingProviderResponse);

export type Llm4AdEmbeddingProvidersListEmbeddingProvidersData = {
    limit?: number;
    skip?: number;
};

export type Llm4AdEmbeddingProvidersListEmbeddingProvidersResponse = (PaginatedEmbeddingProviderResponse);

export type Llm4AdEmbeddingProvidersGetEmbeddingProviderData = {
    providerId: string;
};

export type Llm4AdEmbeddingProvidersGetEmbeddingProviderResponse = (EmbeddingProviderResponse);

export type Llm4AdEmbeddingProvidersUpdateEmbeddingProviderData = {
    providerId: string;
    requestBody: EmbeddingProviderUpdate;
};

export type Llm4AdEmbeddingProvidersUpdateEmbeddingProviderResponse = (EmbeddingProviderResponse);

export type Llm4AdEmbeddingProvidersDeleteEmbeddingProviderData = {
    providerId: string;
};

export type Llm4AdEmbeddingProvidersDeleteEmbeddingProviderResponse = (Message);

export type Llm4AdLlmproxyProxyLlmData = {
    path: string;
};

export type Llm4AdLlmproxyProxyLlmResponse = (unknown);

export type Llm4AdLlmproxyProxyLlm1Data = {
    path: string;
};

export type Llm4AdLlmproxyProxyLlm1Response = (unknown);

export type Llm4AdLlmproxyProxyLlm2Data = {
    path: string;
};

export type Llm4AdLlmproxyProxyLlm2Response = (unknown);

export type Llm4AdLlmproxyProxyLlm3Data = {
    path: string;
};

export type Llm4AdLlmproxyProxyLlm3Response = (unknown);

export type Llm4AdLlmproxyProxyLlm4Data = {
    path: string;
};

export type Llm4AdLlmproxyProxyLlm4Response = (unknown);

export type Llm4AdLlmproxyProxyLlm5Data = {
    path: string;
};

export type Llm4AdLlmproxyProxyLlm5Response = (unknown);

export type Llm4AdProjectsCreateProjectData = {
    requestBody: ProjectCreate;
};

export type Llm4AdProjectsCreateProjectResponse = (ProjectResponse);

export type Llm4AdProjectsListProjectsData = {
    limit?: number;
    /**
     * 排序方向，asc 升序 / desc 降序
     */
    order?: string;
    /**
     * 按项目名称或描述模糊搜索（不区分大小写），为空时返回全部
     */
    q?: (string | null);
    skip?: number;
    /**
     * 排序字段，支持 created_time / name
     */
    sort?: string;
};

export type Llm4AdProjectsListProjectsResponse = (PaginatedProjectResponse);

export type Llm4AdProjectsGetProjectData = {
    projectId: string;
};

export type Llm4AdProjectsGetProjectResponse = (ProjectResponse);

export type Llm4AdProjectsUpdateProjectData = {
    projectId: string;
    requestBody: ProjectUpdate;
};

export type Llm4AdProjectsUpdateProjectResponse = (ProjectResponse);

export type Llm4AdProjectsDeleteProjectData = {
    projectId: string;
};

export type Llm4AdProjectsDeleteProjectResponse = (Message);

export type Llm4AdProvidersTestProviderData = {
    requestBody: ProviderTestRequest;
};

export type Llm4AdProvidersTestProviderResponse = (ProviderTestResponse);

export type Llm4AdProvidersCreateProviderData = {
    requestBody: ProviderCreate;
};

export type Llm4AdProvidersCreateProviderResponse = (ProviderResponse);

export type Llm4AdProvidersListProvidersData = {
    limit?: number;
    skip?: number;
};

export type Llm4AdProvidersListProvidersResponse = (PaginatedProviderResponse);

export type Llm4AdProvidersGetBuiltinProviderQuotaResponse = (BuiltinProviderQuotaResponse);

export type Llm4AdProvidersGetLitellmUserQuotasResponse = (LiteLLMUserQuotaListResponse);

export type Llm4AdProvidersGetProviderData = {
    providerId: string;
};

export type Llm4AdProvidersGetProviderResponse = (ProviderResponse);

export type Llm4AdProvidersUpdateProviderData = {
    providerId: string;
    requestBody: ProviderUpdate;
};

export type Llm4AdProvidersUpdateProviderResponse = (ProviderResponse);

export type Llm4AdProvidersDeleteProviderData = {
    providerId: string;
};

export type Llm4AdProvidersDeleteProviderResponse = (Message);

export type Llm4AdProvidersTestStoredProviderData = {
    providerId: string;
    requestBody: ProviderTestByIdRequest;
};

export type Llm4AdProvidersTestStoredProviderResponse = (ProviderTestResponse);

export type Llm4AdReportsGetReportTemplatesResponse = (ReportTemplatesResponse);

export type Llm4AdReportsGenerateReportData = {
    requestBody: ReportGenerateRequest;
    taskId: string;
};

export type Llm4AdReportsGenerateReportResponse = (ReportGenerateResponse);

export type Llm4AdReportsGetReportData = {
    reportType: ReportType;
    taskId: string;
};

export type Llm4AdReportsGetReportResponse = (ReportDetailResponse);

export type Llm4AdReportsStopReportData = {
    reportType: ReportType;
    taskId: string;
};

export type Llm4AdReportsStopReportResponse = (ReportStopResponse);

export type Llm4AdReportsStreamReportData = {
    reportType: ReportType;
    taskId: string;
};

export type Llm4AdReportsStreamReportResponse = (unknown);

export type Llm4AdReportsGenerateAdviseData = {
    requestBody: AdvisorGenerateRequest;
    taskId: string;
};

export type Llm4AdReportsGenerateAdviseResponse = (AdvisorGenerateResponse);

export type Llm4AdReportsGetAdviseData = {
    taskId: string;
};

export type Llm4AdReportsGetAdviseResponse = (AdvisorDetailResponse);

export type Llm4AdReportsGenerateRecommendData = {
    requestBody: AdvisorGenerateRequest;
    taskId: string;
};

export type Llm4AdReportsGenerateRecommendResponse = (AdvisorGenerateResponse);

export type Llm4AdReportsGetRecommendData = {
    taskId: string;
};

export type Llm4AdReportsGetRecommendResponse = (AdvisorDetailResponse);

export type Llm4AdTasksListExampleTemplatesResponse = (ExampleTemplateListResponse);

export type Llm4AdTasksListTasksData = {
    limit?: number;
    /**
     * 项目ID
     */
    projectId: string;
    skip?: number;
};

export type Llm4AdTasksListTasksResponse = (PaginatedTaskResponse);

export type Llm4AdTasksGetTaskData = {
    taskId: string;
};

export type Llm4AdTasksGetTaskResponse = (TaskResponse);

export type Llm4AdTasksUpdateTaskData = {
    requestBody: TaskUpdate;
    taskId: string;
};

export type Llm4AdTasksUpdateTaskResponse = (TaskResponse);

export type Llm4AdTasksDeleteTaskData = {
    taskId: string;
};

export type Llm4AdTasksDeleteTaskResponse = (Message);

export type Llm4AdTasksCreateTaskData = {
    requestBody: TaskCreate;
};

export type Llm4AdTasksCreateTaskResponse = (TaskResponse);

export type Llm4AdTasksUpdateTaskTagData = {
    requestBody: TaskTagUpdate;
    taskId: string;
};

export type Llm4AdTasksUpdateTaskTagResponse = (TaskResponse);

export type Llm4AdTasksSetActiveChildData = {
    requestBody: SetActiveChildRequest;
    taskId: string;
};

export type Llm4AdTasksSetActiveChildResponse = (TaskResponse);

export type Llm4AdTasksGetTaskTreeData = {
    taskId: string;
};

export type Llm4AdTasksGetTaskTreeResponse = (TaskTreeResponse);

export type Llm4AdTasksCopyTaskData = {
    requestBody?: TaskCopyRequest;
    taskId: string;
};

export type Llm4AdTasksCopyTaskResponse = (TaskResponse);

export type Llm4AdTasksRunTaskData = {
    taskId: string;
};

export type Llm4AdTasksRunTaskResponse = (TaskRunResponse);

export type Llm4AdTasksStopTaskData = {
    taskId: string;
};

export type Llm4AdTasksStopTaskResponse = (TaskResponse);

export type Llm4AdTasksGetTaskResultData = {
    taskId: string;
};

export type Llm4AdTasksGetTaskResultResponse = (TaskResultResponse);

export type Llm4AdTasksGetTaskStatsData = {
    taskId: string;
};

export type Llm4AdTasksGetTaskStatsResponse = (TaskStatsResponse);

export type Llm4AdTasksGenerateResultRenderData = {
    requestBody: ResultRenderGenerateRequest;
    taskId: string;
};

export type Llm4AdTasksGenerateResultRenderResponse = (ResultRenderGenerateResponse);

export type Llm4AdTasksGetConfigSchemaData = {
    taskId: string;
};

export type Llm4AdTasksGetConfigSchemaResponse = (AppConfigSchemaResponse);

export type Llm4AdTasksDownloadTaskWorkspaceData = {
    taskId: string;
};

export type Llm4AdTasksDownloadTaskWorkspaceResponse = (unknown);

export type Llm4AdTasksUploadTaskDataData = {
    formData: tasks_upload_task_data;
    taskId: string;
};

export type Llm4AdTasksUploadTaskDataResponse = (Message);

export type Llm4AdTasksGetTaskDataTreeData = {
    taskId: string;
};

export type Llm4AdTasksGetTaskDataTreeResponse = (FileTreeResponse);

export type Llm4AdTasksCreateTaskDataFileData = {
    requestBody: FileCreateRequest;
    taskId: string;
};

export type Llm4AdTasksCreateTaskDataFileResponse = (FileCreateResponse);

export type Llm4AdTasksGetTaskDataFileData = {
    /**
     * 文件相对路径
     */
    filePath: string;
    taskId: string;
};

export type Llm4AdTasksGetTaskDataFileResponse = (FileContentResponse);

export type Llm4AdTasksUpdateTaskDataFileData = {
    requestBody: FileUpdateRequest;
    taskId: string;
};

export type Llm4AdTasksUpdateTaskDataFileResponse = (Message);

export type Llm4AdTasksDeleteTaskDataFileData = {
    /**
     * 文件相对路径
     */
    filePath: string;
    taskId: string;
};

export type Llm4AdTasksDeleteTaskDataFileResponse = (Message);

export type Llm4AdTasksRenameTaskDataFileData = {
    requestBody: FileRenameRequest;
    taskId: string;
};

export type Llm4AdTasksRenameTaskDataFileResponse = (Message);

export type Llm4AdTasksCreateTaskDataFolderData = {
    requestBody: FolderCreateRequest;
    taskId: string;
};

export type Llm4AdTasksCreateTaskDataFolderResponse = (FolderCreateResponse);

export type Llm4AdTasksDeleteTaskDataFolderData = {
    /**
     * 待删除文件夹的相对路径
     */
    folderPath: string;
    taskId: string;
};

export type Llm4AdTasksDeleteTaskDataFolderResponse = (Message);

export type Llm4AdTasksRenameTaskDataFolderData = {
    requestBody: FolderRenameRequest;
    taskId: string;
};

export type Llm4AdTasksRenameTaskDataFolderResponse = (Message);

export type Llm4AdTasksGetTaskLogsData = {
    /**
     * 分页游标，首次请求不传，后续传上一次返回的 next_cursor
     */
    cursor?: (string | null);
    /**
     * 按日志级别过滤，支持多选
     */
    level?: (Array<(string)> | null);
    /**
     * 每页条数，0 表示不分页返回全部
     */
    limit?: number;
    /**
     * 按日志类型过滤
     */
    logType?: (string | null);
    /**
     * 全文搜索日志内容
     */
    q?: (string | null);
    taskId: string;
};

export type Llm4AdTasksGetTaskLogsResponse = (TaskLogsResponse);

export type Llm4AdTasksStreamTaskLogsData = {
    taskId: string;
};

export type Llm4AdTasksStreamTaskLogsResponse = (unknown);

export type Llm4AdTasksCodeAuthResponse = (unknown);

export type Llm4AdUserDefaultModelsGetUserDefaultModelResponse = (UserDefaultModelResponse);

export type Llm4AdUserDefaultModelsUpdateUserDefaultModelData = {
    requestBody: UserDefaultModelUpdate;
};

export type Llm4AdUserDefaultModelsUpdateUserDefaultModelResponse = (UserDefaultModelResponse);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginRefreshAccessTokenData = {
    requestBody: RefreshAccessToken;
};

export type LoginRefreshAccessTokenResponse = (Token);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type PermissionCreateData = {
    requestBody: PermissionBase;
};

export type PermissionCreateResponse = (unknown);

export type PermissionGetData = {
    pk: unknown;
};

export type PermissionGetResponse = (unknown);

export type PermissionPermissionsResponse = (unknown);

export type PrivacyPolicyGetPrivacyPolicyContentData = {
    lang?: string;
};

export type PrivacyPolicyGetPrivacyPolicyContentResponse = (PrivacyPolicyContent);

export type PrivacyPolicyAcceptPrivacyPolicyAuthenticatedResponse = (Message);

export type PrivacyPolicyAcceptPrivacyPolicyBeforeLoginData = {
    requestBody: AcceptPrivacyPolicyRequest;
};

export type PrivacyPolicyAcceptPrivacyPolicyBeforeLoginResponse = (UserPublic);

export type PrivacyPolicyCheckPrivacyPolicyStatusResponse = ({
    [key: string]: unknown;
});

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserRegisterResponse);

export type UsersVerifyEmailData = {
    requestBody: VerifyEmailRequest;
};

export type UsersVerifyEmailResponse = (Message);

export type UsersResendVerifyCodeData = {
    requestBody: ResendVerifyCodeRequest;
};

export type UsersResendVerifyCodeResponse = (ResendVerifyCodeResponse);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type UtilsCodeServerGetCodeTokenData = {
    /**
     * True for dark theme, False for light theme
     */
    dark?: boolean;
};

export type UtilsCodeServerGetCodeTokenResponse = (unknown);

export type UtilsTestingTestS3Response = (Message);

export type UtilsTestingTestCurrentUserDpResponse = (unknown);

export type UtilsTestingTestCurrentUserResponse = (unknown);

export type UtilsTestingTestSuperuserDpResponse = (unknown);

export type UtilsTestingTestSuperuserResponse = (unknown);

export type UtilsTestingTestRequirePermissionDpResponse = (unknown);

export type UtilsTestingTestGetTaskInfoData = {
    taskId: string;
};

export type UtilsTestingTestGetTaskInfoResponse = (unknown);